---
collections:
  # Core collections for general automation
  - name: community.general
    version: ">=8.0.0"

  # POSIX-specific modules (file, mount, etc.)
  - name: ansible.posix
    version: ">=1.5.0"

  # Docker container management
  - name: community.docker
    version: ">=3.4.0"

  # Crypto operations (certificates, keys)
  - name: community.crypto
    version: ">=2.0.0"

  # AWS automation (if needed)
  - name: amazon.aws
    version: ">=7.0.0"

  # Google Cloud automation (if needed)
  - name: google.cloud
    version: ">=1.3.0"
